name: Run Telegram Bot
on:
  workflow_dispatch:      # Запуск кнопкой

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }} # ЭТО САМАЯ ВАЖНАЯ СТРОЧКА
        run: node index.js
